spring:
  datasource:
    schema: classpath:db/${DATABASE_TYPE}/schema.sql
    data: classpath:db/${DATABASE_TYPE}/data.sql
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=false
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialize: ${DATABASE_INIT}
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      write-dates-as-timestamps: true    

monitor:
  enabled: true 
